// Copyright 2026 Lablup Inc. Licensed under the Apache License, Version 2.0.
export const modelStrings = [
  {
    key: 'models.library.subtitle',
    en: 'Inspect local checkpoints. Selecting never loads a model.',
    ko: '로컬 체크포인트를 확인하세요. 선택만으로 모델을 로드하지 않습니다.',
    test_id: 'models-library-subtitle',
  },
  {
    key: 'models.library.search',
    en: 'Search local models',
    ko: '로컬 모델 검색',
    test_id: 'models-library-search',
  },
  {
    key: 'models.library.source',
    en: 'Source',
    ko: '소스',
    test_id: 'models-library-source',
  },
  {
    key: 'models.library.task',
    en: 'Task',
    ko: '작업',
    test_id: 'models-library-task',
  },
  {
    key: 'models.library.status',
    en: 'Lifecycle',
    ko: '수명주기',
    test_id: 'models-library-status',
  },
  {
    key: 'models.library.sort',
    en: 'Sort',
    ko: '정렬',
    test_id: 'models-library-sort',
  },
  {
    key: 'models.library.name',
    en: 'Model',
    ko: '모델',
    test_id: 'models-library-name',
  },
  {
    key: 'models.library.all',
    en: 'All',
    ko: '전체',
    test_id: 'models-library-all',
  },
  {
    key: 'models.library.add',
    en: 'Add Model',
    ko: '모델 추가',
    test_id: 'models-library-add',
  },
  {
    key: 'models.library.rescan',
    en: 'Rescan local roots',
    ko: '로컬 경로 다시 검색',
    test_id: 'models-library-rescan',
  },
  {
    key: 'models.library.refresh',
    en: 'Refresh server state',
    ko: '서버 상태 새로고침',
    test_id: 'models-library-refresh',
  },
  {
    key: 'models.library.roots',
    en: 'Configured roots',
    ko: '설정된 경로',
    test_id: 'models-library-roots',
  },
  {
    key: 'models.library.roots_help',
    en: 'To change roots, restart the server with your local directory. This command is an example, not an executed action.',
    ko: '경로를 변경하려면 로컬 디렉터리를 지정하여 서버를 다시 시작하세요. 아래 명령은 예시이며 자동 실행되지 않습니다.',
    test_id: 'models-library-roots-help',
  },
  {
    key: 'models.library.single',
    en: 'Single-model mode: lifecycle and cache changes are read-only. Restart without -m to manage models.',
    ko: '단일 모델 모드: 수명주기 및 캐시는 읽기 전용입니다. 모델을 관리하려면 -m 없이 다시 시작하세요.',
    test_id: 'models-library-single',
  },
  {
    key: 'models.library.unknown',
    en: 'Unknown',
    ko: '알 수 없음',
    test_id: 'models-library-unknown',
  },
  {
    key: 'models.library.yes',
    en: 'Yes',
    ko: '예',
    test_id: 'models-library-yes',
  },
  {
    key: 'models.library.no',
    en: 'No',
    ko: '아니요',
    test_id: 'models-library-no',
  },
  {
    key: 'models.library.inspect',
    en: 'Inspect {name}',
    ko: '{name} 자세히 보기',
    test_id: 'models-library-inspect',
  },
  {
    key: 'models.library.selected',
    en: 'Selected',
    ko: '선택됨',
    test_id: 'models-library-selected',
  },
  {
    key: 'models.library.details',
    en: 'Model details',
    ko: '모델 상세',
    test_id: 'models-library-details',
  },
  {
    key: 'models.library.support',
    en: 'Support / completeness',
    ko: '지원 / 완전성',
    test_id: 'models-library-support',
  },
  {
    key: 'models.library.supported',
    en: 'Supported architecture',
    ko: '지원되는 아키텍처',
    test_id: 'models-library-supported',
  },
  {
    key: 'models.library.unsupported',
    en: 'Unsupported architecture',
    ko: '지원되지 않는 아키텍처',
    test_id: 'models-library-unsupported',
  },
  {
    key: 'models.library.complete',
    en: 'Complete files',
    ko: '파일 완전함',
    test_id: 'models-library-complete',
  },
  {
    key: 'models.library.incomplete',
    en: 'Incomplete files',
    ko: '불완전한 파일',
    test_id: 'models-library-incomplete',
  },
  {
    key: 'models.library.architecture',
    en: 'Architecture',
    ko: '아키텍처',
    test_id: 'models-library-architecture',
  },
  {
    key: 'models.library.backend',
    en: 'Runnable on this backend',
    ko: '현재 백엔드 실행 가능',
    test_id: 'models-library-backend',
  },
  {
    key: 'models.library.tested',
    en: 'Checkpoint validated',
    ko: '검증된 체크포인트',
    test_id: 'models-library-tested',
  },
  {
    key: 'models.library.tested_help',
    en: 'Family support does not prove this checkpoint was tested.',
    ko: '계열 지원은 해당 체크포인트의 검증을 의미하지 않습니다.',
    test_id: 'models-library-tested-help',
  },
  {
    key: 'models.library.disk',
    en: 'Disk size',
    ko: '디스크 크기',
    test_id: 'models-library-disk',
  },
  {
    key: 'models.library.memory',
    en: 'Estimated memory (not measured)',
    ko: '예상 메모리 (측정값 아님)',
    test_id: 'models-library-memory',
  },
  {
    key: 'models.library.context',
    en: 'Effective context (tokens)',
    ko: '실제 컨텍스트 (토큰)',
    test_id: 'models-library-context',
  },
  {
    key: 'models.library.profile',
    en: 'Next-load profile',
    ko: '다음 로드 프로필',
    test_id: 'models-library-profile',
  },
  {
    key: 'models.library.defaults',
    en: 'Server defaults; see Settings for scope and overrides.',
    ko: '서버 기본값입니다. 범위와 재정의는 설정에서 확인하세요.',
    test_id: 'models-library-defaults',
  },
  {
    key: 'models.library.error',
    en: 'Action could not complete',
    ko: '작업을 완료하지 못함',
    test_id: 'models-library-error',
  },
  {
    key: 'models.library.last_error',
    en: 'Last server error',
    ko: '최근 서버 오류',
    test_id: 'models-library-last-error',
  },
  {
    key: 'models.library.chat',
    en: 'Use in Chat',
    ko: '채팅에서 사용',
    test_id: 'models-library-chat',
  },
  {
    key: 'models.library.chat_reason',
    en: 'Chat requires a ready provider with an available chat capability. Other tasks remain available through their API.',
    ko: '채팅에는 준비된 제공자와 사용 가능한 채팅 기능이 필요합니다. 다른 작업은 API로 사용하세요.',
    test_id: 'models-library-chat-reason',
  },
  {
    key: 'models.library.api',
    en: 'API task documentation',
    ko: 'API 작업 문서',
    test_id: 'models-library-api',
  },
  {
    key: 'models.library.delete',
    en: 'Delete cached files',
    ko: '캐시 파일 삭제',
    test_id: 'models-library-delete',
  },
  {
    key: 'models.library.delete_body',
    en: 'Permanently delete the managed cache entry {name} ({source}). This removes files from disk, unlike Unload. Type the model name to confirm.',
    ko: '관리 캐시 항목 {name} ({source})을 영구 삭제합니다. 언로드와 달리 디스크 파일을 제거합니다. 모델 이름을 입력하여 확인하세요.',
    test_id: 'models-library-delete-body',
  },
  {
    key: 'models.library.confirm_name',
    en: 'Exact cache model ID to confirm',
    ko: '확인용 정확한 캐시 모델 ID',
    test_id: 'models-library-confirm-name',
  },
  {
    key: 'models.library.unload_body',
    en: 'Unload {name} ({source}): {count} active requests must drain before the worker exits. Files remain on disk. A timeout is a failure, not a completed unload.',
    ko: '{name} ({source}) 언로드: 활성 요청 {count}개를 배출한 뒤 작업자가 종료됩니다. 디스크 파일은 유지됩니다. 시간 초과는 완료가 아닌 실패입니다.',
    test_id: 'models-library-unload-body',
  },
  {
    key: 'models.library.confirm',
    en: 'Confirm',
    ko: '확인',
    test_id: 'models-library-confirm',
  },
  {
    key: 'models.library.cancel',
    en: 'Cancel',
    ko: '취소',
    test_id: 'models-library-cancel',
  },
  {
    key: 'models.library.repo',
    en: 'Public HuggingFace repo ID',
    ko: '공개 HuggingFace 저장소 ID',
    test_id: 'models-library-repo',
  },
  {
    key: 'models.library.revision',
    en: 'Revision (optional)',
    ko: '리비전 (선택)',
    test_id: 'models-library-revision',
  },
  {
    key: 'models.library.network',
    en: 'Only this explicit action contacts HuggingFace. Files go to the server-managed cache below. Size is unknown until the server resolves file metadata. Search never contacts external services.',
    ko: '이 작업을 명시적으로 실행할 때만 HuggingFace에 연결합니다. 파일은 아래 서버 관리 캐시에 저장됩니다. 크기는 서버가 파일 메타데이터를 확인할 때까지 알 수 없습니다. 검색은 외부 서비스에 연결하지 않습니다.',
    test_id: 'models-library-network',
  },
  {
    key: 'models.library.public',
    en: 'This is a public, ungated repository',
    ko: '공개된 비게이트 저장소입니다',
    test_id: 'models-library-public',
  },
  {
    key: 'models.library.private',
    en: 'Private or gated downloads are unavailable in the WebUI. Use an authenticated HuggingFace CLI outside the server, then rescan a configured local root. Do not paste credentials here.',
    ko: '비공개 또는 게이트 다운로드는 WebUI에서 지원하지 않습니다. 서버 외부에서 인증된 HuggingFace CLI를 사용한 뒤 설정된 로컬 경로를 다시 검색하세요. 여기에 인증 정보를 입력하지 마세요.',
    test_id: 'models-library-private',
  },
  {
    key: 'models.library.repo_invalid',
    en: 'Enter owner/repository, not a URL or a local path.',
    ko: 'URL이나 로컬 경로가 아닌 소유자/저장소를 입력하세요.',
    test_id: 'models-library-repo-invalid',
  },
  {
    key: 'models.library.operations',
    en: 'Library operations',
    ko: '라이브러리 작업',
    test_id: 'models-library-operations',
  },
  {
    key: 'models.library.pending',
    en: 'Request outcome is being reconciled. Do not resubmit; refresh to observe the server operation.',
    ko: '요청 결과를 확인하고 있습니다. 재제출하지 말고 새로고침하여 서버 작업을 확인하세요.',
    test_id: 'models-library-pending',
  },
  {
    key: 'models.library.retry_download',
    en: 'Retry download',
    ko: '다운로드 재시도',
    test_id: 'models-library-retry-download',
  },
  {
    key: 'models.library.cancel_download',
    en: 'Cancel download',
    ko: '다운로드 취소',
    test_id: 'models-library-cancel-download',
  },
  {
    key: 'models.library.cancel_body',
    en: 'Cancel the download of {name}? Unpublished partial files are not a usable model.',
    ko: '{name} 다운로드를 취소할까요? 공개되지 않은 부분 파일은 사용할 수 있는 모델이 아닙니다.',
    test_id: 'models-library-cancel-body',
  },
  {
    key: 'models.library.progress',
    en: 'Download progress',
    ko: '다운로드 진행률',
    test_id: 'models-library-progress',
  },
  {
    key: 'models.library.worker',
    en: 'Worker exit observed',
    ko: '작업자 종료 확인',
    test_id: 'models-library-worker',
  },
  {
    key: 'models.library.stale',
    en: 'State changed or is not current. Refresh, inspect the latest revision, and explicitly confirm again.',
    ko: '상태가 변경되었거나 최신이 아닙니다. 새로고침하고 최신 리비전을 확인한 뒤 다시 명시적으로 확인하세요.',
    test_id: 'models-library-stale',
  },
  {
    key: 'models.library.capacity',
    en: 'Capacity / conflicting operation',
    ko: '용량 / 작업 충돌',
    test_id: 'models-library-capacity',
  },
  {
    key: 'models.library.capacity_body',
    en: 'Do not repeatedly load. Review active models below. If capacity is full, explicitly choose an idle ready model to unload before this load. Busy models are never offered as eviction targets. Eviction is not rolled back if the new load fails.',
    ko: '반복해서 로드하지 마세요. 아래 활성 모델을 확인하세요. 용량이 가득 차면 이번 로드 전에 언로드할 유휴 준비 모델을 명시적으로 선택하세요. 사용 중인 모델은 교체 대상으로 제공되지 않습니다. 새 로드 실패 시 교체는 되돌려지지 않습니다.',
    test_id: 'models-library-capacity-body',
  },
  {
    key: 'models.library.eviction',
    en: 'Explicit eviction target',
    ko: '명시적 교체 대상',
    test_id: 'models-library-eviction',
  },
  {
    key: 'models.library.choose',
    en: 'Choose a model',
    ko: '모델 선택',
    test_id: 'models-library-choose',
  },
  {
    key: 'models.library.evict_load',
    en: 'Unload target and load',
    ko: '대상 언로드 후 로드',
    test_id: 'models-library-evict-load',
  },
  {
    key: 'models.library.active',
    en: 'Active requests',
    ko: '활성 요청',
    test_id: 'models-library-active',
  },
  {
    key: 'models.library.page',
    en: 'Page {page} of {pages} · {count} models',
    ko: '{pages}페이지 중 {page} · 모델 {count}개',
    test_id: 'models-library-page',
  },
  {
    key: 'models.library.previous',
    en: 'Previous page',
    ko: '이전 페이지',
    test_id: 'models-library-previous',
  },
  {
    key: 'models.library.next',
    en: 'Next page',
    ko: '다음 페이지',
    test_id: 'models-library-next',
  },
  {
    key: 'models.library.filtered',
    en: 'No matching local models',
    ko: '일치하는 로컬 모델 없음',
    test_id: 'models-library-filtered',
  },
  {
    key: 'models.library.filtered_body',
    en: 'Change the local search or filters.',
    ko: '로컬 검색어나 필터를 변경하세요.',
    test_id: 'models-library-filtered-body',
  },
  {
    key: 'models.library.waiting',
    en: 'Waiting for an authoritative catalog snapshot',
    ko: '서버의 카탈로그 스냅샷을 기다리는 중',
    test_id: 'models-library-waiting',
  },
  {
    key: 'models.library.sort_name',
    en: 'Name (A–Z)',
    ko: '이름 (오름차순)',
    test_id: 'models-library-sort-name',
  },
  {
    key: 'models.library.sort_status',
    en: 'Lifecycle',
    ko: '수명주기',
    test_id: 'models-library-sort-status',
  },
  {
    key: 'models.library.sort_source',
    en: 'Source',
    ko: '소스',
    test_id: 'models-library-sort-source',
  },
  {
    key: 'models.library.sort_task',
    en: 'Task',
    ko: '작업',
    test_id: 'models-library-sort-task',
  },
  {
    key: 'models.library.unavailable',
    en: 'Not available for this server or model',
    ko: '현재 서버 또는 모델에서 사용할 수 없음',
    test_id: 'models-library-unavailable',
  },
  {
    key: 'models.library.permission',
    en: 'Root could not be read. Check server directory permissions, then rescan.',
    ko: '경로를 읽지 못했습니다. 서버 디렉터리 권한을 확인한 뒤 다시 검색하세요.',
    test_id: 'models-library-permission',
  },
  {
    key: 'models.library.copy',
    en: 'Copy command',
    ko: '명령 복사',
    test_id: 'models-library-copy',
  },
  {
    key: 'models.library.copied',
    en: 'Copied',
    ko: '복사됨',
    test_id: 'models-library-copied',
  },
  {
    key: 'models.library.copy_failed',
    en: 'Select and copy the command below.',
    ko: '아래 명령을 선택하여 복사하세요.',
    test_id: 'models-library-copy-failed',
  },
  {
    key: 'models.library.accepted',
    en: 'Accepted; waiting for observed server state.',
    ko: '접수됨. 서버에서 관측된 상태를 기다리는 중입니다.',
    test_id: 'models-library-accepted',
  },
  {
    key: 'models.library.operation_state',
    en: 'Operation state',
    ko: '작업 상태',
    test_id: 'models-library-operation-state',
  },
] as const;
