import React, { act } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { LiveSettings } from './live-settings';
import type { SettingsResponse } from '../../api/settings';
const actions = vi.hoisted(() => ({ getSettings: vi.fn(), patchSettings: vi.fn() }));
vi.mock('../../state', () => ({ useWebUiActions: () => actions }));
let host: HTMLDivElement; let root: Root;
const make = (fingerprint = 'a', temperature = 1): SettingsResponse => ({ schema: [{ name: 'default_temperature', type: 'float', default: 0.8, mutable: true, allowed: null, help: 'Temperature' }, { name: 'default_top_p', type: 'float', default: 0.9, mutable: true, allowed: null, help: 'Top P' }, { name: 'n_parallel', type: 'int', default: 1, mutable: false, allowed: null, reason: 'worker-owned; restart', help: 'Slots' }], current: { default_temperature: temperature, default_top_p: 1, n_parallel: 1 }, fingerprint: fingerprint.repeat(64) });
beforeEach(() => { vi.clearAllMocks(); host = document.createElement('div'); document.body.append(host); root = createRoot(host); HTMLDialogElement.prototype.showModal = function () { this.setAttribute('open', ''); }; HTMLDialogElement.prototype.close = function () { this.removeAttribute('open'); }; });
afterEach(() => { act(() => root.unmount()); host.remove(); });
async function render(model = 'model-a'): Promise<void> { await act(async () => { root.render(<LiveSettings modelId={model} locale="en" />); }); }
async function button(label: string): Promise<void> { const element = [...host.querySelectorAll('button')].find((item) => item.textContent === label); expect(element).toBeDefined(); await act(async () => element?.click()); }
async function edit(name: string, value: string): Promise<void> { const field = [...host.querySelectorAll('label')].find((item) => item.querySelector('span')?.textContent === name)?.querySelector('input'); expect(field).toBeTruthy(); await act(async () => { Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value')?.set?.call(field, value); field?.dispatchEvent(new Event('input', { bubbles: true })); }); }
describe('live settings partial/stale/reset behavior', () => {
  it('reports disabled endpoint and never submits a mutation', async () => { actions.getSettings.mockRejectedValue(new Error('404')); await render(); expect(host.textContent).toContain('may have disabled --settings'); expect(actions.patchSettings).not.toHaveBeenCalled(); });
  it('preserves rejected input, removes applied input and refetches effective values', async () => { actions.getSettings.mockResolvedValueOnce(make()).mockResolvedValueOnce(make()).mockResolvedValueOnce(make('b', 0.5)); actions.patchSettings.mockResolvedValue({ applied: { default_temperature: 0.5 }, rejected: [{ name: 'default_top_p', reason: 'must be between zero and one' }], current: {}, fingerprint: 'b'.repeat(64) }); await render(); await edit('default_temperature', '0.5'); await edit('default_top_p', '2'); await button('Apply live draft'); expect(host.textContent).toContain('1 applied; 1 rejected'); expect(host.textContent).toContain('must be between zero and one'); expect(actions.getSettings).toHaveBeenCalledTimes(3); expect(actions.patchSettings.mock.calls[0][1]).toEqual({ default_temperature: 0.5, default_top_p: 2 }); });
  it('requires reconfirmation after another client edit and stages reset without PATCH', async () => { actions.getSettings.mockResolvedValueOnce(make()).mockResolvedValue(make('b', 0.2)); await render(); await edit('default_temperature', '0.5'); await button('Apply live draft'); expect(actions.patchSettings).not.toHaveBeenCalled(); expect(host.textContent).toContain('Another client changed'); await button('Reset live draft…'); await button('Reset draft'); expect(actions.patchSettings).not.toHaveBeenCalled(); expect(host.textContent).toContain('worker-owned; restart'); });
  it('ignores a stale fetch after model binding changes', async () => { let resolve: ((value: SettingsResponse) => void) | undefined; actions.getSettings.mockImplementationOnce(() => new Promise<SettingsResponse>((done) => { resolve = done; })).mockResolvedValueOnce(make('b', 0.7)); await render(); await render('model-b'); await act(async () => resolve?.(make('a', 99))); expect(host.textContent).not.toContain('Current: 99'); expect(host.textContent).toContain('Current: 0.7'); });
});
